spring.application.name=mastercard-dispute-management
spring.datasource.url=jdbc:postgresql://localhost:5432/dispute_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mastercard API Configuration
mastercard.base-url=https://sandbox.api.mastercard.com
mastercard.consumer-key=***REMOVED_MASTERCARD_CONSUMER_KEY***
mastercard.keystore-password=***REMOVED_MASTERCARD_KEYSTORE_PASSWORD***
mastercard.keystore-path=src\\main\\resources\\Opus Dispute Management System-sandbox-signing.p12
