spring.application.name=mastercard-dispute-management
spring.datasource.url=jdbc:postgresql://localhost:5432/dispute_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mastercard API Configuration
mastercard.base-url=https://sandbox.api.mastercard.com
mastercard.consumer-key=0XR45cMyVFyHbVpZD65m3KxYlizpsdvIKLQLC56Xc99a95c1!a4e7f28d99c149aba73936d6f9646cb50000000000000000
mastercard.keystore-password=Mastercard-0pus-dispute-key
mastercard.keystore-path=src\\main\\resources\\Opus Dispute Management System-sandbox-signing.p12
